from __future__ import annotations

import csv
import json
import os
from dataclasses import asdict
from pathlib import Path

from huggingface_hub import HfApi, batch_bucket_files

from hia.human_calibration import HumanLabel, evaluate_human_calibration

ROOT = Path(__file__).resolve().parents[1]
INPUT = Path(os.getenv("HIA_HUMAN_REVIEW_CSV", ROOT / "artifacts" / "human_review_queue.csv"))
OUT = ROOT / "artifacts" / "calibration_report.json"
DATASET_REPO = "h0000w/Human-Intelligence-Assurance-Lab"
BUCKET = "h0000w/Human-Intelligence-Assurance-Lab-storage"


def _parse_bool(value: str) -> bool | None:
    normalized = value.strip().lower()
    if normalized in {"true", "1", "yes", "pass"}:
        return True
    if normalized in {"false", "0", "no", "fail"}:
        return False
    return None


def main() -> None:
    rows = list(csv.DictReader(INPUT.open(encoding="utf-8", newline="")))
    labels: list[HumanLabel] = []
    for row in rows:
        human = _parse_bool(row.get("human_pass", ""))
        judge = _parse_bool(row.get("judge_pass", ""))
        if human is None or judge is None:
            continue
        reviewer = (row.get("reviewer_id") or row.get("reviewer") or "").strip()
        if not reviewer:
            raise ValueError(f"reviewer provenance missing for scenario {row.get('scenario_id', 'unknown')}")
        adjudicated = _parse_bool(row.get("adjudicated_pass", ""))
        labels.append(
            HumanLabel(
                sample_id=(row.get("sample_id") or row.get("scenario_id") or "").strip(),
                reviewer_id=reviewer,
                human_pass=human,
                judge_pass=judge,
                critical=row.get("risk_level") == "critical" or _parse_bool(row.get("critical", "")) is True,
                adjudicated_pass=adjudicated,
            )
        )

    if not labels:
        raise ValueError("no independently labeled rows found")

    result = evaluate_human_calibration(labels)
    payload = {
        "schema_version": "1.9",
        "source": str(INPUT),
        "reviewer_count": result.reviewer_count,
        "reviewed_samples": result.sample_count,
        "unresolved_samples": result.unresolved_count,
        "inter_reviewer_kappa": result.inter_reviewer_kappa,
        "report": asdict(result.judge_calibration) if result.judge_calibration else None,
        "semantic_release_critical": result.ready_for_release,
        "reasons": list(result.reasons),
        "note": (
            "Calibration metrics use only explicit human labels with reviewer provenance. "
            "At least two independent reviewers per sample are required; disagreements need explicit adjudication. "
            "No human labels are generated by this program."
        ),
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(json.dumps(payload, indent=2))

    token = os.getenv("HF_TOKEN")
    if token:
        api = HfApi(token=token)
        api.upload_file(
            path_or_fileobj=str(OUT),
            path_in_repo="runs/calibration_report.json",
            repo_id=DATASET_REPO,
            repo_type="dataset",
        )
        batch_bucket_files(BUCKET, add=[(str(OUT), "runs/calibration_report.json")], token=token)

    if not result.ready_for_release:
        raise SystemExit(2)


if __name__ == "__main__":
    main()
